/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : article-posting

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2020-10-04 23:00:15
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `articles`
-- ----------------------------
DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `published_at` date NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `amount_viewer` bigint(20) NOT NULL,
  `video_link` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `category_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `status` varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `articles_category_id_foreign` (`category_id`),
  KEY `articles_user_id_foreign` (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of articles
-- ----------------------------
INSERT INTO `articles` VALUES ('1', '2020-07-27', 'sit-sit-aut-quis-nemo-velit', 'Blanditiis amet ut et ea voluptas error.', 'Magnam recusandae eius autem harum enim ut consequuntur. Quaerat magni cupiditate esse qui et molestiae. Omnis aperiam fuga ipsum nam et voluptatibus voluptas accusantium. Quia est vel at et rem voluptas ut. Voluptatem et explicabo est odit error sed. Id aliquid commodi magni ducimus. Illo eos sit accusamus nisi assumenda laborum explicabo voluptas. Et sunt et rerum ut commodi. Mollitia est modi quod cumque reprehenderit odio. Quasi natus culpa laboriosam velit qui ea sit. Repellat sunt quis et occaecati. Voluptas iste consequatur consequatur non saepe laborum. Et qui et non sed alias. Et asperiores sed amet numquam ea eius incidunt quod. Doloremque fuga odio assumenda et non. Soluta est est sapiente expedita. Temporibus eos nostrum magni sit. Eum quia qui voluptatem soluta perspiciatis qui tempore. Aut ullam quo sit voluptas. Autem sed hic voluptas maxime nam voluptatem sint consequatur. Omnis quos eos doloremque et quia sapiente sit.', '251', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('2', '2019-12-16', 'voluptas-neque-sint-fugit-deleniti-mollitia-non-expedita-magnam', 'Qui sequi iste nisi harum quam.', 'Voluptate iste ipsa totam culpa. Maiores nulla porro distinctio aut dolor eius aperiam. Neque quis nobis qui. Saepe aspernatur qui nulla corrupti nesciunt fuga harum. Necessitatibus explicabo veniam quia magnam quo eum. Cumque qui ipsam quia perferendis voluptatem ab. Mollitia qui deserunt similique modi hic et. Atque perspiciatis fugit est quod voluptatem id quia quasi. Autem autem rerum molestiae corporis ut magni. Natus ut in quis delectus aut earum fuga. Sequi aut iusto dicta facilis. Aut possimus tempora sequi officiis porro. Et repudiandae maiores sint dolor eveniet dolor possimus. Deleniti cumque ex quia pariatur quod. Tempora veritatis rem quam molestiae perspiciatis adipisci necessitatibus. Numquam sapiente possimus ut nemo dolor. Accusantium architecto voluptatem asperiores non eum eveniet quas voluptas. Nihil impedit provident illum.', '329', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('3', '2019-12-18', 'nemo-ut-fugiat-aut-est', 'Eligendi quia reprehenderit cupiditate.', 'Dignissimos est incidunt quis dolores quaerat enim. Occaecati a vitae aut consequatur commodi temporibus nihil. Non adipisci qui numquam quo deserunt. Repellendus est magni voluptates quia deleniti. Ut atque officia dolore nemo cum necessitatibus excepturi inventore. Sunt illum eius non reprehenderit. Ut ab veritatis unde qui voluptatem esse. Consectetur laudantium quas omnis alias maxime. Ut voluptate at omnis quas consequatur laboriosam facilis ea. Ducimus quibusdam quaerat quia deserunt et. Sed illum soluta blanditiis in ea nostrum. Molestiae amet officiis voluptas quisquam. Expedita expedita cumque eum fuga illo aperiam. Excepturi rerum unde est et. Eveniet quia reprehenderit vel harum. Non fuga consequatur qui voluptatem in aut laborum accusamus. Quas et harum fugit. Ipsam dignissimos culpa asperiores quia incidunt. Consequuntur et tenetur est nemo quis dolorem.', '296', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('4', '2019-10-28', 'animi-possimus-tempora-perferendis-explicabo-quia', 'Natus aliquam voluptatem voluptatem voluptate commodi.', 'Necessitatibus ex repellendus qui sit non et. Labore possimus vel dolore facere dolorem. Eius reiciendis non est odit. Ipsam consequatur odit sed qui. Debitis ex excepturi sequi impedit asperiores. Minus odio quia porro et tenetur placeat. Voluptas expedita est eos reprehenderit ea minus. Voluptatem explicabo fuga quaerat id voluptas non commodi rerum. Alias natus doloremque qui et deleniti dolore quibusdam. Rerum ea aut animi itaque. Totam nihil impedit corrupti quia cupiditate amet. Occaecati et adipisci error officiis rem modi et. Nulla perferendis quia aut quisquam. Quia et at ut. Ullam ipsa ratione aspernatur autem eos harum dolore. Qui officiis consequatur laboriosam eos soluta qui. Eum unde consequatur magni animi nam sed odit. Quod enim beatae non et. Voluptatum nihil dicta voluptatem beatae voluptas eaque. Et voluptas voluptas in aut labore temporibus. Magnam tempore voluptatem dolores nobis facilis culpa.', '716', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('5', '2020-01-06', 'totam-ullam-architecto-perferendis-incidunt', 'Voluptatum molestias sed adipisci minima perspiciatis iste alias.', 'Necessitatibus repellendus et voluptas minima sint. Voluptate voluptatem perspiciatis tempora dolorem laudantium. Sapiente veritatis tenetur qui aliquid iusto quod et. Perferendis odio sit ut est facilis est dolorum. Fuga quasi expedita est atque velit. Ipsum omnis reprehenderit voluptas dolore non sit. Natus consequatur quaerat maxime iusto aut. Est voluptates aut minus suscipit. Qui provident et tenetur perspiciatis. Dolores voluptates perspiciatis eos corporis esse. Aspernatur rerum repellat nisi nemo quo omnis. Vero voluptatem molestiae eligendi. Sed iste ipsum sed eum consequuntur blanditiis aliquam. Explicabo distinctio quis culpa omnis et asperiores. Eum eaque eos dolores. Sed velit deserunt suscipit omnis est neque. Similique voluptatem iste temporibus delectus non officiis aut officia. Excepturi pariatur esse nostrum aliquid. Atque nihil accusantium rerum esse praesentium quia dignissimos recusandae. Totam sed est omnis sit ex quia veritatis rerum.', '343', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('6', '2020-08-24', 'animi-dolor-dolor-voluptas-commodi-corrupti-eius', 'Fuga atque voluptas placeat sit.', 'Ex deserunt neque repellendus doloremque eum sapiente fugit. Maiores eum consectetur ducimus et molestias. Corporis magni a aut quia rerum voluptatibus. Numquam vel expedita vitae ea non. Libero nihil eum inventore dolorum a. Deserunt adipisci exercitationem odio. Voluptates eaque quis est a ea. Velit dolorum ea ut. Rem quasi perspiciatis rerum consequuntur et impedit. Ipsam ipsam harum est dolor exercitationem enim voluptatem. Doloribus iusto accusantium ut placeat non. Non excepturi sit reiciendis praesentium. Reprehenderit rerum consequatur veniam iure et sed. Sunt consequatur praesentium est sunt iusto blanditiis. Perferendis porro nostrum hic rerum et. Molestias inventore eos ex aperiam ab et. A dolore non ab qui vel voluptatem. Aliquam quo hic dolor. Eaque quam eaque voluptas id quis repudiandae error. Ut optio dolore alias voluptatem. Accusantium aperiam earum unde quis tempore et quis. Cupiditate maiores culpa alias eaque.', '954', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '1', '1', null);
INSERT INTO `articles` VALUES ('7', '2020-05-06', 'nesciunt-quia-dolorem-est-nostrum-provident-et-omnis', 'Quia eaque aliquam velit in sit.', 'Velit animi quam omnis vero molestias. Quia consequatur reprehenderit minima sit nostrum dolore deleniti dolorum. Atque aut qui voluptas eos quisquam eaque sint. Minima eum minima cum repellat. Vero sunt et repudiandae molestias. Quia earum sunt corrupti ducimus eos. Enim quisquam necessitatibus rerum et dignissimos. Molestias et eveniet consequatur dolor illum explicabo. Voluptatem reiciendis eligendi hic accusantium nihil. Explicabo iste ad cumque aliquam. Numquam at ut repudiandae mollitia et saepe rerum doloribus. Commodi tenetur voluptatem vel minus deserunt ut. Neque est aut nostrum dolores. Rerum consequatur rerum eveniet perspiciatis tempore. Sed nesciunt dignissimos officia unde. Natus quo asperiores sed dicta consequatur quaerat vero. Qui quia et quisquam rem. Molestiae minus commodi doloribus et. Qui sed laboriosam eligendi eaque qui deserunt doloremque cumque. Repellat quasi voluptas et laborum quidem itaque et. Deserunt non deserunt sint distinctio quod.', '924', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('8', '2019-10-09', 'in-quia-et-molestias-qui-magnam-culpa', 'Quis et veniam repudiandae repellat ipsa quia.', 'Ipsa quas cupiditate rem asperiores inventore autem cumque. Sit accusamus culpa architecto molestiae a. Autem at inventore velit qui ipsam facere voluptatum. Voluptas iusto in quia. Maxime eveniet minima vel molestiae. Aut incidunt aut alias ut nihil ducimus sapiente omnis. Quas laudantium a corporis quidem laboriosam vitae inventore. Doloribus autem id laudantium nobis non blanditiis. Totam dolores accusantium et maiores quis minima. Dolorum et nulla illum corporis asperiores molestiae minus non. Qui cumque enim nulla explicabo sunt ullam consectetur. Laudantium temporibus nam eligendi quod modi sapiente sit. Amet nihil consequatur eum natus. Quam ea consequatur praesentium eligendi culpa. Reiciendis debitis suscipit laboriosam et asperiores. Saepe modi perferendis eius consequatur hic. Rerum voluptas id aspernatur dolore exercitationem. Assumenda itaque veritatis pariatur accusamus nulla. Expedita mollitia voluptas at autem dolor accusamus in reiciendis.', '543', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '2', '1', null);
INSERT INTO `articles` VALUES ('9', '2020-07-02', 'eveniet-inventore-fuga-dolorum-aut-tenetur', 'Enim non voluptate dolorum.', 'Mollitia eos provident illo odit ab esse est. Voluptatem deleniti natus dolores sed ullam velit. Nihil ex consequuntur blanditiis praesentium. Possimus eum molestias assumenda dolore qui assumenda. Dignissimos sed a dolorem suscipit ratione explicabo. Deleniti ut et quo ad architecto vero. Non sit odit enim voluptatibus maiores qui inventore. Magni suscipit facere odio odio. Rem aut consequuntur fuga ab. Quos sed reiciendis veritatis rerum reprehenderit ut. Cupiditate deleniti odio et ut deleniti inventore unde. Deleniti praesentium est beatae similique. Nobis et doloremque fuga. Corporis optio eos autem suscipit eos assumenda expedita. Omnis quia saepe illum optio corrupti rerum voluptate nihil. Dicta dolorem quis ut et eligendi architecto excepturi. Blanditiis ea exercitationem ipsa accusamus tenetur exercitationem. Ut ipsum nisi culpa hic et repellendus sunt. Voluptatem aliquid ad praesentium voluptas rerum.', '696', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('10', '2020-07-19', 'quidem-autem-et-nostrum-non-ea-dolore', 'Labore sed iusto esse asperiores.', 'Cum reprehenderit et totam qui iste doloremque. Reprehenderit odio ad est quae et. Sunt odit neque voluptas tempora officiis. Dicta consectetur aperiam blanditiis suscipit quos mollitia libero iusto. Cumque quaerat voluptas quidem eos magnam officiis. Sit tempora repellat quam maiores quae distinctio eligendi. Eveniet nihil architecto mollitia voluptas. Soluta nemo amet magnam omnis. Iusto expedita cupiditate corporis dolores fuga natus aut. Non sunt ut est distinctio aut dignissimos maxime veniam. Non voluptas ipsum numquam expedita reprehenderit voluptas. Et et ad praesentium voluptatem rem voluptas. Esse rem atque sunt minus qui recusandae ipsam. Aut nihil deleniti eveniet perspiciatis. Aut illo maxime nemo. Atque aperiam aliquam aut assumenda aut deserunt dignissimos. Harum corporis et ex aut in dicta. Sapiente excepturi repellat culpa eos sequi qui. Qui amet ut modi eius reprehenderit porro. Facere et sint beatae dicta sit placeat reprehenderit itaque.', '342', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('11', '2020-03-14', 'iure-facilis-labore-sit', 'Facilis ipsam magnam sit aliquid harum et quibusdam.', 'Officiis quis adipisci recusandae ut excepturi ut. Nulla et quam ut et unde sapiente. Velit dolor qui consequatur laboriosam enim quia cumque. Laborum doloremque cupiditate vero dolores. Maxime officiis optio voluptas magnam. Ipsa iusto sit harum voluptatem quae et molestiae. Culpa modi eligendi alias ut. Dignissimos sed laborum eius. Reiciendis voluptate est veniam maxime modi. Tempore dignissimos sunt et. Quidem ut voluptate quae ut sit. Earum quia quia dolorum deserunt. Voluptate cumque et qui magnam officia eos. Optio error eos et quaerat. Aut dolorem quas consectetur numquam maxime doloremque. Dolorem cupiditate reiciendis ea expedita. Delectus consequatur id unde consequatur. Eos quia qui aliquid hic aliquam excepturi et quia. Voluptas sed possimus atque. Minima nostrum qui ipsum natus optio. Architecto necessitatibus nobis voluptate. Autem recusandae soluta itaque. Cumque illum accusantium iusto sed ut eius non. Omnis libero eligendi alias accusamus corporis in facere.', '164', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('12', '2020-03-14', 'alias-suscipit-architecto-placeat-et-cum-aut', 'Aperiam corrupti ipsum ad fugiat sunt illum enim.', 'Voluptas deserunt saepe aut nisi labore et optio. Nihil exercitationem qui repudiandae. Sed voluptatem sed ut sit ipsum vitae. Odit aperiam qui iure unde et odio. Nam architecto ut occaecati. Ut quia beatae consequatur pariatur nihil ut. At ut ducimus aut asperiores culpa dolor voluptatem. Voluptatem magni incidunt enim ullam asperiores. Qui accusamus enim commodi est qui. Adipisci doloribus omnis veritatis velit. Nisi minus corporis facere accusantium explicabo odio. Tempora cum quo rerum. Ipsa ea id optio est. Dolorem in quam sapiente deserunt dolor. Reiciendis voluptas esse illo et expedita. Magni in quia mollitia facilis veniam sint est. Aspernatur debitis quod qui facere eum ea qui quae. Aut molestias ad sed porro suscipit nesciunt. Ratione velit vel maiores non non eaque.', '778', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('13', '2020-07-12', 'molestiae-id-possimus-illo-debitis-nisi-alias-perspiciatis', 'Odit dolor sint quis.', 'Repudiandae ex cupiditate dolores aperiam harum recusandae voluptas. Magnam molestias perspiciatis reiciendis magni voluptates sunt. At harum ratione qui voluptatum consequuntur sint. Ratione velit praesentium ipsum occaecati. Explicabo repellat ut natus accusamus quasi tempora ipsum. Ut rerum aut non cum est quidem. Reiciendis perferendis fuga quod asperiores doloremque et. Et qui earum dolores iure odio eum. Est quasi sapiente quas qui. Aut ea praesentium a. Perspiciatis voluptas ut deleniti quis quia ad voluptas. Esse iste ipsa iste unde aspernatur consequatur molestiae. Iure et dolorem magnam totam aut quas quis. Dolore consequatur ut omnis quia voluptatem repellat atque tempore. Quibusdam consequatur pariatur quis modi aut eum et modi. Qui perferendis et eum autem dolorum voluptatibus et qui. Vitae possimus voluptatum voluptas. Ut similique eos repudiandae aut molestiae eos voluptatibus.', '542', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('14', '2019-10-06', 'quia-ducimus-enim-natus-fugit-expedita-temporibus-a-velit', 'Quia ut voluptatem nobis nobis autem cumque neque.', 'Earum repellendus ducimus qui quia. Est vitae ipsa aperiam harum nihil ab id. Nisi accusantium doloribus perspiciatis quod. Et sunt eum sapiente tenetur est voluptatem dolores. Harum autem fuga molestiae. Voluptatum consequatur molestiae eligendi. Vitae sed et laboriosam. Et reiciendis unde at et. Eius ipsum quia quia corrupti. Voluptatem molestias et earum itaque impedit. Earum nostrum enim sed expedita. Repellendus illum est illo voluptatem dolor. Fugit quia magni debitis illo mollitia nulla accusamus. Nihil officiis praesentium aliquid aliquam ipsam recusandae. Sed reprehenderit ab officia et optio incidunt vero. Eveniet non minima minima occaecati sequi tenetur ullam. Cumque est doloremque at quo. Eos et sed voluptates error qui dolor reiciendis. Eius sed provident enim minima molestiae nisi. Officia id aut quo ullam. Hic omnis repudiandae nostrum. Non et eius inventore culpa vero repellendus enim quisquam. Deleniti aut error corporis sit in possimus nihil.', '381', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '1', '1', null);
INSERT INTO `articles` VALUES ('15', '2020-02-28', 'quia-voluptas-officia-et-assumenda-quisquam', 'Vero pariatur veniam nostrum quia possimus explicabo et.', 'Fuga odit deleniti beatae voluptas beatae fugit ea. Et totam velit natus non corrupti incidunt quaerat. Cum amet non est enim dolores. Quia nobis quia iure aperiam commodi sit eum. Et velit dignissimos enim aut quo omnis aliquid. Praesentium impedit occaecati magni et. Aut voluptas ut amet dolor omnis maiores dolores nulla. Harum incidunt porro voluptas enim eos. Et natus harum ducimus deserunt deserunt. Quod ducimus velit exercitationem totam autem. Voluptas ea rem impedit saepe voluptas fugiat ex. Et consequatur et sit maiores doloremque fugiat nobis quis. Velit laborum qui beatae aperiam est. Dolorum dolorem dolore dolorum amet quia et maxime et. Laudantium aut at perspiciatis voluptate harum ut. Dignissimos quae sint iure dolorem. Aut dolorem est nesciunt sit nesciunt tempore. Libero velit recusandae in et ipsum unde. Vero harum aut non cupiditate minus itaque ut. Est fugit saepe placeat et dolores. Veniam qui et recusandae error adipisci.', '806', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '1', '1', null);
INSERT INTO `articles` VALUES ('16', '2020-01-22', 'rem-harum-quia-tenetur-sit', 'Voluptatibus consequuntur consequatur repellendus magnam dolores qui.', 'Ipsam expedita et placeat sit ut sunt est suscipit. Reiciendis autem velit voluptate eum et. Impedit qui inventore distinctio odit fugiat veritatis soluta. Aut eos et qui beatae est non. Accusantium et quidem deserunt quis delectus dolorum dolor. Ea deleniti laborum amet reiciendis dolores. Saepe quia animi iure et ipsam. Neque minima animi assumenda qui beatae corrupti dolor. Consequatur quis non impedit sint error quas. Nihil aut beatae praesentium cum dolor. Ut voluptate velit quas. Sed sit ea voluptatem molestiae porro. Error dolor et dolore eius voluptatem alias explicabo. Sint quia qui nostrum quisquam placeat minima id. Tempore ullam atque minima repellat saepe libero. Ipsum dolores at dignissimos cumque. Quae quam reiciendis et non. Autem neque harum non voluptatem. Possimus quis harum perferendis voluptas saepe rerum voluptas. Quia rerum nobis qui sit. Ducimus provident vero ut excepturi quia distinctio soluta.', '351', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('17', '2019-11-21', 'dignissimos-assumenda-vel-et-voluptatem-qui', 'Doloribus et laborum eos voluptatem.', 'Voluptatibus cum corporis id veritatis veritatis voluptas. Est voluptatem non autem quaerat sit dolorem. Inventore debitis repudiandae cumque enim delectus error molestiae est. Laudantium expedita voluptatem aut eum. Vero ab et dicta recusandae distinctio neque voluptas voluptates. Assumenda est reprehenderit numquam est consectetur. Laudantium dolores ducimus voluptatibus voluptas id accusamus. In sequi et itaque et nisi. Adipisci cupiditate et nulla. Provident quo magni iste aut. Rem et voluptas exercitationem numquam perspiciatis consequatur. Aliquid quos cupiditate dolorem architecto quo. Dolore sunt aliquam sit est sequi ab commodi. Delectus dolores vero quos. Qui autem voluptate quia ipsa aut sunt corporis autem. Et et quo nihil temporibus autem aut. Impedit id voluptas voluptatem dolorum consequatur. Illo dolores consequatur ullam sed qui est quae. Atque ex dolorem veritatis perspiciatis adipisci consequatur vitae. Quae error ut inventore. Aut cum aspernatur nihil quidem et.', '180', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '2', '1', null);
INSERT INTO `articles` VALUES ('18', '2020-07-01', 'accusantium-aperiam-rem-sint-velit-ut-voluptatibus-est-quis', 'Quis placeat quaerat veniam perferendis.', 'Accusantium natus dolores debitis aliquid fuga et molestiae. Voluptates minus eos unde possimus. Atque harum in ut omnis tenetur. Similique dolor et et in et enim corrupti. Magnam eos asperiores aut dolorum. Id laudantium dolorem sapiente voluptatem ut corporis. Natus quo ut exercitationem nulla. Cumque error est voluptas rem at sunt et. Et dicta voluptatem reiciendis maiores sed officiis quos. Amet officia vero magnam voluptatem tempora voluptatum. Vero alias explicabo rerum accusantium aperiam iste vitae. Libero mollitia harum repudiandae expedita aut molestias expedita soluta. Dicta qui aut modi accusamus ipsam. Similique autem repellendus rerum voluptate veritatis fuga. Ratione dolorem maiores ipsam quas voluptas ullam omnis. Consectetur fugiat eius quos alias autem. Vel ut quaerat quis amet repudiandae nihil ab facere. Eius quas accusantium quia repudiandae. Ipsum enim quisquam sed rem accusantium. Ut illo facilis maxime est quia.', '819', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('19', '2020-02-26', 'perspiciatis-voluptatem-sit-et-eos', 'Eaque enim qui sint voluptas et.', 'Porro quis enim itaque voluptatem cum quam veniam. At voluptas labore consequatur voluptatem delectus id. Consequatur veritatis velit explicabo repudiandae perferendis. Beatae molestiae officiis facilis veniam. Est ut dolores rem nisi. Dolorem recusandae alias illo laboriosam similique iure. Voluptatem repellendus omnis dolore voluptatibus. Fugit repellendus nobis voluptatem laboriosam similique iusto. Quo aut sed reprehenderit perferendis dignissimos magni perspiciatis. Itaque provident minima molestiae laboriosam consectetur et ab. Id amet voluptatem sit dignissimos quia aut. Aspernatur sit doloremque vero quisquam assumenda. Facilis facilis dolorem amet ratione dicta unde. Ea dolorem molestiae quae vitae nihil. Repellendus veniam enim ad dolorum. Dicta suscipit unde voluptatem sint voluptate.', '137', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '1', '1', null);
INSERT INTO `articles` VALUES ('20', '2019-12-03', 'voluptate-omnis-modi-voluptates-aut-et-rerum', 'Nobis sit in porro eum repellat eum quas.', 'Dolore enim labore recusandae id similique. Sint amet consequatur temporibus nam velit numquam. Neque id consectetur exercitationem id. Voluptatem et et ut voluptatem porro voluptas. Exercitationem sit aut possimus omnis perferendis ut sed excepturi. Id nemo quae hic autem. Vel sint id velit. Vel iusto aliquam voluptatem est et voluptates. Saepe dolores quod amet eos dignissimos. Et enim architecto maxime repellendus qui omnis aut. Quam quisquam quaerat ducimus magni. Dolorem saepe et autem deleniti ipsam omnis. Corporis laborum aut labore corrupti. Dicta excepturi est sint incidunt et. Voluptate alias ullam quia quis molestiae magni voluptatem. Nobis corporis sapiente consectetur dolores modi atque eum. Non molestiae ullam consequatur officiis ut consectetur velit aliquid. Cum perspiciatis nulla cum autem sapiente. Minima quia consequatur velit omnis nulla omnis. Unde qui facilis aut aliquid voluptatibus.', '502', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '2', '1', null);
INSERT INTO `articles` VALUES ('21', '2020-04-28', 'similique-aliquid-aut-rerum-eaque-assumenda-et', 'Incidunt neque accusantium dolor hic veritatis.', 'Voluptatum dolores tempora neque hic. Labore qui sint nemo quis dignissimos totam id. Et qui eligendi a est numquam. Et totam aut similique soluta rerum. Dolorem repellendus blanditiis quia voluptates et molestiae laudantium. Dicta ut animi id distinctio soluta ipsum qui. Ipsum quam vel sed rerum dicta optio. Quia est consequatur inventore nihil qui. Eligendi in aliquam laborum nihil at delectus sint. Et aliquam sint et sint aut. Repudiandae eius ut rerum qui. Dolorum sapiente reiciendis voluptatum eligendi quaerat consequatur. Quia officiis veniam laudantium quas. Eaque ut aut iste. Modi maiores voluptatem et eius accusamus quasi quia. Asperiores laudantium optio et et voluptas. Eum reiciendis sit iure voluptatem non vel et. Aliquid sit earum quasi est iusto ea aliquam tempora. Eveniet ut voluptatem illo. Omnis cupiditate ut provident sunt sit ut omnis. Laboriosam laborum rem explicabo fugiat.', '530', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('22', '2020-08-24', 'et-voluptatem-ducimus-qui-ut-dolor-voluptates', 'Quibusdam enim nisi sint quisquam.', 'Aut ullam culpa dolor qui. Eum nisi sit fugiat rerum. Quia cupiditate quisquam reiciendis ut odio assumenda. Libero et sit dolorum. Voluptatum tenetur cumque aperiam aliquid. Velit voluptas sed voluptatem consequatur veritatis. Id et nihil quis ut animi sed. Corrupti ad eligendi porro voluptatibus. Illo aut enim sed neque voluptas repudiandae labore. Modi et facere animi iste id at impedit molestiae. Recusandae qui alias id possimus itaque quo. Ducimus voluptatem animi veritatis laboriosam aspernatur. Quo eius nisi nihil blanditiis deserunt sed. Accusamus rerum perferendis sit. Suscipit ea illum fugit voluptatem error. Non officiis sunt iure rerum veniam voluptatem ea. Perspiciatis dolorum necessitatibus qui quia enim voluptatum. Et sit aut fugiat tempora nam. Neque dolor ex alias commodi id. Libero delectus laudantium reiciendis minus. Alias quia adipisci ut fuga. Hic voluptatem molestiae incidunt iusto ex sapiente fugiat.', '926', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('23', '2020-06-15', 'voluptatum-officia-inventore-tempore', 'Odit saepe nemo ratione aspernatur.', 'Tempora a deserunt dolore vel voluptatem expedita. Amet et aliquam sit blanditiis qui ipsa laboriosam. Incidunt quia animi id amet est alias. Voluptas aliquid distinctio voluptatem ad non perferendis aut. Eligendi consequatur aperiam nihil earum. Amet soluta quia quia. Voluptatibus est consectetur perspiciatis ut voluptatem et illum. Inventore illum exercitationem et. Molestias accusantium repellat delectus laborum perferendis et provident qui. Omnis dolores culpa omnis vel sunt. Cupiditate explicabo ut quaerat error. Amet beatae voluptatem veritatis amet ut. Harum ipsum exercitationem aperiam voluptates est nam nesciunt et. Harum aut saepe asperiores consequuntur molestiae distinctio natus. Earum est et cumque in consequatur quae quos necessitatibus. Veritatis dolor expedita voluptatem non sit. Quia modi cum et quo est officiis. Id aperiam explicabo voluptates. Eligendi aut et qui natus ad.', '580', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '1', '1', null);
INSERT INTO `articles` VALUES ('24', '2020-08-06', 'aut-facere-eos-error-facilis-rerum', 'Aut dolorum dignissimos consectetur blanditiis.', 'Facilis a maxime quasi a soluta. Velit esse neque distinctio provident placeat consequatur. Nobis provident eum temporibus voluptatem unde voluptatem. Quod et maxime molestiae ex ut at nemo. Distinctio ut sit rem qui molestias quas modi veritatis. Et commodi id et dolore consequuntur. Ea vero magni rem incidunt corporis in cupiditate ut. Illum dolor rerum culpa non. Eos aliquam optio est. Beatae dolor distinctio omnis. Perferendis non et soluta hic. Deleniti fugiat at enim non. Accusantium ut harum possimus sed. Aspernatur non praesentium sed consectetur. Vel pariatur sint velit repellat. Deleniti omnis est ullam id autem. Labore quas at optio et maiores. Saepe aut ut omnis dolorem blanditiis possimus. Eum nostrum et et cum saepe quos molestiae. Architecto repellendus voluptatem quia officia consequuntur. Aut sed voluptatibus reiciendis debitis eos qui consequatur. Laboriosam quos sed commodi et maxime dolor nobis et.', '784', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '2', '1', null);
INSERT INTO `articles` VALUES ('25', '2020-03-23', 'eos-dicta-veniam-aut-earum-soluta-tenetur', 'Consequatur veritatis hic deleniti aut.', 'Rem quam aspernatur corporis atque tenetur sint magnam. Deleniti dolores itaque aliquid quaerat voluptatum sunt sed. Est ab eaque non enim. Esse odio quas cumque et temporibus qui blanditiis omnis. Ad eos maiores minima similique voluptatibus qui delectus. Error sunt dicta animi dolorum. Sed autem suscipit iure ut non. Est amet et ab quaerat dolor. Vel aliquam ratione officia. Et eveniet ut qui ut. Quaerat sapiente vel nam blanditiis amet enim. Dicta enim voluptas vitae placeat sint possimus. Velit ipsa et nobis officiis saepe reiciendis sed. Facilis iusto iste porro distinctio ratione blanditiis ipsa voluptatem. Eum eveniet quos unde omnis tempora cum. Cumque similique et dolorum molestiae dolorum dolor et. Id recusandae qui consectetur. Explicabo magni quod accusantium consequatur nam. Eos quae ea et aperiam consequatur. Ex mollitia eum omnis iure.', '945', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('26', '2019-12-18', 'delectus-et-ipsam-delectus-iste-illo-voluptatibus', 'Qui et id aliquid.', 'Excepturi eveniet molestiae dolor voluptates amet commodi. Ratione non eum quia occaecati sed. Est dignissimos adipisci deleniti omnis. Aliquid eaque tempore ea quo. Animi et iure vel voluptates. Aspernatur ullam pariatur ab aliquid repudiandae. Labore veritatis ratione quia sint blanditiis. In nisi dolor ex eveniet sed. Dolorem corporis et mollitia quae. Est voluptatem praesentium quia voluptas itaque eligendi repellat nostrum. Non ut quo necessitatibus distinctio ipsum. Autem ea nisi consequatur voluptatem fugit. Facere sit qui quis. Eos molestiae consequatur sunt sunt aut voluptatem. Quae optio voluptas qui dicta et mollitia. Non provident ipsum maxime vero ea dolor. Corrupti omnis aliquid occaecati laboriosam. Autem facere consequatur eligendi repellat quo nihil. Voluptas sint commodi voluptatum aut eaque exercitationem. Eligendi reprehenderit quas est. Ipsa aut tempore culpa expedita nihil qui et.', '242', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '1', '1', null);
INSERT INTO `articles` VALUES ('27', '2019-10-15', 'autem-possimus-minus-architecto-modi', 'Molestiae rerum sint voluptatem adipisci tempore id ut.', 'Mollitia dolor labore ratione ut perferendis magni enim. Magnam sed laudantium dolores sint eum sed ex. Reiciendis perferendis corrupti consectetur. Ea eos cupiditate ratione. Explicabo quae repellendus inventore molestiae sint error et. Voluptates id inventore corporis ullam. Dolor eum ad rerum. Consequatur et et consequatur non quia cupiditate quis. Deserunt quasi laboriosam sit est deserunt architecto. Et ut quidem in soluta molestias. Impedit accusamus rerum facere quaerat pariatur est. Ipsum autem aperiam qui cupiditate eius consequuntur. Eos soluta suscipit sunt voluptas. Repudiandae vero voluptas maiores quo ab rerum. Aut qui quod rerum exercitationem quia quia nostrum. Iste quia velit totam deserunt et consequuntur eveniet. Asperiores corporis minima repudiandae quia quia nam. Est fugit esse sapiente dolor ratione quasi quas. Aut eum ipsa enim laborum alias omnis. Eum consequuntur minima vitae.', '983', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('28', '2020-07-28', 'nihil-nostrum-aut-illo-consequuntur-aut-saepe', 'Sed molestiae quia vitae iusto expedita reiciendis inventore.', 'Delectus culpa fugiat autem ex. Exercitationem dicta facere tempore dolor. Doloribus quos rerum est autem accusantium. Ullam voluptate non dicta nemo. Aut reprehenderit magni autem repudiandae et est. Laboriosam aperiam earum esse. Quo dolor animi sint qui quis quod pariatur nihil. Neque nisi praesentium at esse quae. Inventore veniam numquam nemo voluptatem ipsam harum impedit. Vel est aut qui. Distinctio natus nostrum eum nulla dolor quasi. Est et sapiente expedita et quo ea. Asperiores ab nostrum consequatur. Ipsam neque nisi nobis ut. Accusamus incidunt maxime modi et quia qui. Est qui vitae sit odit facilis. Itaque molestias sapiente aut non. Enim dolores sed et harum sit. Fugiat omnis aperiam hic sit inventore facilis. Quas ut perferendis velit et maiores soluta. Incidunt sit atque molestias voluptatibus.', '433', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '2', '1', null);
INSERT INTO `articles` VALUES ('29', '2019-10-22', 'cupiditate-praesentium-ad-et-enim-amet-optio-suscipit', 'Repudiandae fugiat veritatis vel reiciendis.', 'Sequi praesentium provident velit accusantium omnis non debitis. Et odit unde quidem laborum ab. Ut ex debitis pariatur sunt. At facere voluptatibus quaerat. Dolorem eaque voluptas voluptas quasi quod illo maiores. Velit consequatur modi illum et. Autem sit sit eos et. Incidunt nam commodi autem consequatur dolor dolores et. Repellat sequi fuga porro voluptas qui. Quo possimus quis sit aut consequatur. Et at ratione consequatur veniam. Fuga excepturi dolore dolore vitae rem. Et officia aut quos. Distinctio esse dolore quod sed rerum consequatur. Dignissimos explicabo tempore quas eveniet nesciunt impedit aut. Perferendis quo amet nulla eveniet. Quidem quidem velit laborum voluptas est. Dicta sapiente iure recusandae ipsam non. Maiores qui labore et accusamus. Sed in explicabo voluptatum eos et autem omnis. Consectetur iusto dolore est repellendus explicabo tempora. Eius porro corporis omnis quos ea neque.', '524', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('30', '2020-05-21', 'est-eaque-dignissimos-commodi-eum-ullam-fugit', 'Placeat inventore similique consequatur ipsum aliquid numquam.', 'Modi dolore dicta nostrum sint. Molestias numquam facilis laborum odit possimus. Esse sed qui voluptas fuga. Quia rerum nisi id adipisci. Asperiores ut molestiae suscipit aut iusto tenetur voluptate. Natus omnis eum beatae aliquam blanditiis nemo recusandae. Distinctio sint et rerum illo sint nisi commodi quia. Totam dolore illum similique ipsum eaque provident. Repellat vero sit nesciunt dolor eum impedit et. Deserunt vel facilis omnis nihil sed odit cum. Harum officia et adipisci qui amet possimus. Quos temporibus suscipit vero libero atque adipisci. Rerum magnam aut sed iusto et. In eveniet asperiores eum est sunt dolorum molestias. Corporis voluptas non qui velit qui vel dolorem. Nesciunt ut alias exercitationem rem distinctio veniam. Minima illo harum ea. Quidem voluptas eius maiores reiciendis iste est ut. Et quia iure inventore ullam nisi quas. Eos enim distinctio architecto sint rerum. Et quia consequatur voluptatem numquam deserunt. Eveniet vitae quo quibusdam ut similique.', '903', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '2', '1', null);
INSERT INTO `articles` VALUES ('31', '2020-08-03', 'harum-dolorem-reprehenderit-vel-libero', 'Id veniam ullam deserunt quia deserunt quo unde rerum.', 'Temporibus cumque est eum nostrum quis quae modi. Recusandae quis qui rerum inventore fuga. Molestias labore nobis harum est quidem nihil. Non numquam harum temporibus explicabo aut necessitatibus. Perspiciatis et impedit molestias et ut occaecati. Velit eius sit suscipit quae consequatur eaque. Et voluptatem molestias nam dolor. Aperiam id quo voluptates cum. Ad quae autem rerum quia libero. Ea natus ullam distinctio explicabo nemo. Nesciunt vel sed minus aut molestias. Minima provident eveniet soluta est. Id nulla sint repudiandae modi aspernatur. Quo pariatur consequuntur odit sint error et sit. Aut dignissimos sequi labore neque ratione. Ea at nesciunt fugiat vel consequatur. Cumque ab harum est molestiae consequatur non repellendus. Ut perspiciatis quo voluptas sit facilis laboriosam dolores. Molestiae et consequuntur temporibus hic vitae at rerum. Facere ut similique sit neque sunt molestiae repellendus.', '652', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('32', '2020-02-13', 'suscipit-quae-omnis-qui-facere-aliquam-eius', 'Et debitis eos quas molestiae vitae.', 'Quod quos omnis delectus non iusto aut. Nisi eum tempore doloribus velit. Ullam eius vel est et. Eum doloribus a officiis. Magni repudiandae pariatur quia iure ipsum. Rerum ratione aspernatur nulla consectetur. Dolorem non amet vel cumque quibusdam. Sequi nihil facilis earum autem eum et. Voluptatem repellendus tenetur non laudantium. Veniam et eaque consequuntur facere ut aperiam. Impedit amet saepe exercitationem quasi maiores. Voluptate quae quia veritatis. Sunt in consequatur doloremque ut eum in quo. Est consequatur explicabo non qui. Cupiditate in amet ad officiis. Ratione qui amet eveniet et aut praesentium. Accusamus beatae illo ratione itaque. Ut reprehenderit dolores mollitia et fugiat praesentium vitae sit. Voluptas velit ipsum voluptatum et quam et sit. Quis temporibus eius corporis laudantium aut vel earum. Nesciunt modi ea qui corporis. Et tempora deserunt culpa ea incidunt in.', '537', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '1', '1', null);
INSERT INTO `articles` VALUES ('33', '2020-02-27', 'magnam-quis-rem-necessitatibus-vero-provident-itaque-corporis-et', 'Quam quisquam non aperiam veniam incidunt deleniti.', 'Sit laudantium est eveniet beatae molestiae nostrum nisi. Aperiam sit accusamus non iusto doloremque quos sit. Quia est velit soluta hic quo tempore sit. Optio aut illum placeat suscipit minima rerum est. Quia accusantium nihil autem recusandae similique. Totam repellendus ea ratione nobis dolorum iusto eius. Et cupiditate quisquam aut modi quaerat dolores nemo dicta. Quia mollitia nisi sunt et. Voluptatem sunt nulla quidem sed illo ut qui. Accusamus id exercitationem est quo molestiae voluptatem incidunt atque. Perferendis rerum reprehenderit quos commodi incidunt. Unde et ad cupiditate quia est nam. Assumenda nam aliquid facilis perferendis nisi voluptas dignissimos. Possimus quo ut rem. Et voluptates ut at sit dolor. Voluptatem dolores repudiandae rem consequuntur amet dolores. Nulla alias quam saepe. Iste sapiente fugiat sapiente excepturi accusamus asperiores. Voluptatibus error vero sit doloribus asperiores beatae. Sit repellendus earum dolorem nobis quas.', '605', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '2', '1', null);
INSERT INTO `articles` VALUES ('34', '2020-09-09', 'eaque-dolorem-velit-mollitia-cumque', 'Repellat molestiae quibusdam distinctio omnis sed et dolores tempora.', 'Omnis rerum ullam est sit quod eveniet. Modi aut iure totam itaque fuga nobis. Qui tenetur cum modi et ea ipsam. Sequi quis quia iure qui cum. Repudiandae voluptas fugiat praesentium voluptatibus. Qui maxime deleniti sed est architecto illum soluta. Numquam assumenda ut quasi ab dolor distinctio. Veritatis qui veniam soluta facilis aspernatur. Exercitationem voluptatum natus aut corporis. Soluta commodi voluptas ut praesentium dignissimos in. Voluptatem sequi molestias ratione porro et quo. Veritatis vitae sed illo temporibus. Aperiam voluptatibus enim omnis qui laboriosam. Ut placeat error expedita praesentium quis. Nemo deserunt natus odit sapiente magnam rerum dolores nemo. Blanditiis harum ad tempore saepe culpa hic maiores quis. Non quos eaque saepe nam harum ab. Provident eligendi id sint. Qui laboriosam nemo sit non dolorum consectetur non.', '830', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('35', '2020-04-06', 'voluptates-nisi-accusamus-nostrum-dolores-sed', 'Autem in dolorem recusandae tenetur.', 'Corrupti harum ut adipisci cupiditate excepturi excepturi. Hic soluta et ut facilis repellat asperiores. Velit nemo quasi voluptatum quaerat ipsam quasi repudiandae. Aliquid non odio et aliquam incidunt. Rerum iste quos modi quisquam. Mollitia voluptatem commodi sequi. Voluptas sed sed enim natus ea numquam nam non. Rerum quaerat itaque et id eum sed inventore. Asperiores quasi qui iusto maxime. Accusamus consequatur sequi dolore et. Soluta nihil ipsam et autem autem. Est reprehenderit ea delectus dolorem iste qui doloremque ut. Qui voluptatem et nobis rerum dicta dolor. Dolore a quos placeat accusamus sed. Veniam voluptates et magni est. Ab similique voluptatibus sed temporibus laboriosam et consequatur. Tenetur sit quia molestiae perspiciatis. Veniam nam maxime eveniet quo quis repellat. Minus mollitia ullam aut ut. Blanditiis harum in ducimus architecto quasi. Atque est est provident doloremque excepturi eligendi. Dolores illum sunt fuga.', '311', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('36', '2020-05-28', 'asperiores-aut-repellat-vero-ea', 'Dicta fugiat iusto dolorum quas.', 'Quia qui voluptatem consequuntur. Praesentium sed fuga dolorem expedita libero quia adipisci. Mollitia repellendus perspiciatis expedita vel quas voluptatibus. Ducimus similique et qui molestias. Incidunt corrupti in quos placeat ipsa harum veritatis. Veritatis exercitationem veniam delectus necessitatibus vel voluptas suscipit. Non consequatur et et commodi. Qui eum quia quisquam qui doloremque adipisci aut. Et ut ut ipsa adipisci dolorum quam. Velit ea ipsum nobis enim voluptatem ullam labore. Similique fugit et ipsam omnis dicta ut. Consequatur dolorem eum aut omnis. Et quo consequatur earum quis. Vitae earum corporis optio doloribus consequatur in dolores. Delectus soluta qui id dolores et qui. Consequuntur placeat quasi voluptas fugiat nam temporibus et. Eum ut tempore non exercitationem mollitia non. Qui voluptas quasi aperiam consequatur.', '142', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '1', '1', null);
INSERT INTO `articles` VALUES ('37', '2020-01-11', 'autem-qui-non-itaque-nisi-ut', 'Aliquam consequuntur dolorem nulla similique.', 'Consequuntur aut dolorem nostrum illo. Facilis repellat ipsam sunt unde et. Excepturi sapiente qui et maiores omnis quidem. Omnis molestiae excepturi non beatae repudiandae non magnam consectetur. Asperiores eum ratione velit sapiente. In quod maiores soluta et illo dicta. Molestiae commodi earum dicta temporibus iste adipisci debitis. Quisquam consequatur et neque sint. Corrupti blanditiis velit iure in laborum esse. Modi repudiandae eum atque est aut. Adipisci quis quis perferendis eius quidem reprehenderit totam. Est eaque esse sit consectetur ullam voluptatibus sit. Harum debitis iste voluptatibus facere quasi. Minima ut nobis similique quia impedit officia quas esse. Ipsam placeat veritatis beatae dolores. Ad id quasi explicabo ut autem aut quis. Sunt vitae nemo amet cupiditate laboriosam et delectus. Quos quidem voluptatem temporibus ut eaque explicabo porro. Saepe amet quam non nemo sequi.', '294', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('38', '2020-05-24', 'quis-minus-omnis-itaque-autem-magnam', 'Dolorem possimus perferendis esse.', 'Cupiditate neque temporibus veritatis reprehenderit voluptas maxime voluptatum. Ullam nihil sunt placeat laboriosam consequatur consequuntur impedit repudiandae. Aut est quas aspernatur culpa. Est fugiat aliquid optio nobis et voluptas. Dolore ipsam ratione ab minima ut et. Ut possimus commodi autem odio porro. Laudantium veritatis consectetur id facilis praesentium optio illum. Quas impedit et natus ipsa autem. Deserunt quia in libero amet quia sunt. Quia doloremque ea eaque voluptates veritatis adipisci quam. Animi rerum reprehenderit voluptate earum non est asperiores. Ex sed dolorem placeat unde necessitatibus voluptas repellat. In illum deserunt voluptate doloribus provident. Ut quis ducimus itaque alias. Aliquam laudantium perferendis officiis voluptas laudantium eligendi illo rerum. Rerum unde dolorem deleniti molestiae officia. In eum aut magnam reiciendis soluta. Omnis sed ad accusamus quia.', '280', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('39', '2020-09-02', 'repudiandae-non-at-eos', 'Ducimus et sunt iusto sapiente debitis incidunt et.', 'Non rerum aut qui sed dicta officiis. Qui dolorem est quibusdam consequatur dolores occaecati reiciendis quasi. Et et tenetur et amet et placeat. Et ut doloremque assumenda unde. Sequi et eos quibusdam quis voluptatem ut. Veniam ea ad magnam aut ut. Iure iusto perspiciatis quia officiis perspiciatis quasi. Et aut et rerum rem cum unde excepturi. In beatae quaerat nostrum vero. Sit neque aperiam eius ratione quaerat nam natus repudiandae. Consequatur deleniti non accusantium qui. Cumque quia eius quis et nobis. Quae eos autem qui necessitatibus. Voluptatibus et est ipsa quia maxime aut. Ut quam at sit in delectus consequuntur id quia. Distinctio expedita repellat neque illo accusamus est. Doloremque omnis reprehenderit dicta commodi aspernatur et. Recusandae quia enim numquam officiis tempore voluptas praesentium. Blanditiis at quod earum voluptate quisquam illum sequi. Ipsam tempora minima vel molestiae consequuntur ut. Ab non ut perspiciatis explicabo rerum impedit et.', '914', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '1', '1', null);
INSERT INTO `articles` VALUES ('40', '2020-03-14', 'optio-totam-alias-modi-reprehenderit-quis-qui-voluptas', 'Voluptatem ipsam doloremque magni tempora sequi exercitationem omnis.', 'At quis perferendis mollitia consequatur possimus. Quidem sequi architecto voluptatum illo voluptatem. Aliquid alias molestiae quia doloremque labore aliquid sint. Fugiat blanditiis placeat cum id omnis. Sequi hic quibusdam illo commodi eum sunt. Autem quia est voluptatum libero sint placeat ratione. Voluptas ut rem unde dolor ut quia. Sunt quidem consectetur molestias voluptas pariatur velit. Deserunt culpa tempora in id nobis totam. Velit est enim illum ullam. Qui doloribus dolore iure molestiae architecto. Cum ratione odit id repudiandae quis qui. Aut voluptas vitae blanditiis voluptas. Dolor recusandae possimus odio illo rerum non. Quas soluta aspernatur eos qui nesciunt. Vero impedit voluptas voluptatem nihil a. Illo nihil est quis rerum mollitia voluptatibus eos. Voluptas ullam consequatur voluptatem nihil.', '407', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('41', '2020-06-28', 'aut-eveniet-nihil-quo-ea-dignissimos-sapiente', 'Voluptas aliquid rerum iusto reiciendis odio a corrupti.', 'Nobis minima excepturi incidunt qui. Sint et quis sed voluptatum. At esse dolores asperiores cupiditate ratione et atque. Suscipit sit est laboriosam aut aut aut natus repellat. Architecto explicabo qui alias in impedit non. Possimus quasi omnis a. Est illum iure nihil doloremque aspernatur aliquam occaecati. Impedit labore sunt voluptas et sit. Commodi nesciunt aliquam eos quaerat rerum natus. Quia quod necessitatibus eos voluptas. Qui illum dolores eos cupiditate et. Labore sunt autem omnis dignissimos. Placeat quisquam eos dolores nulla et sed. Deserunt architecto reiciendis fuga quidem est modi. Accusantium dolorum et esse dolor optio velit ut. Omnis accusamus architecto incidunt consequatur temporibus possimus voluptatem. Atque possimus et repudiandae. Alias adipisci rerum rem voluptas rerum nihil numquam. Exercitationem consequatur atque dolores exercitationem temporibus eveniet. Architecto et dolorem repellendus itaque. Minima maiores enim corporis in magnam.', '785', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '2', '1', null);
INSERT INTO `articles` VALUES ('42', '2019-10-14', 'ea-totam-saepe-dicta-quibusdam', 'Consequatur fuga ratione aspernatur rerum reiciendis.', 'Distinctio amet aut eius explicabo et sint tenetur. Deleniti quo magni adipisci. Quam illo quis nihil suscipit adipisci consequatur qui voluptatem. Ut autem nemo totam voluptatibus omnis nihil quia explicabo. Voluptatum consequuntur fugiat quidem est. Ea molestiae magnam quis atque tenetur earum. Consectetur optio consequatur libero enim iure iure quis. Laboriosam quia quam dignissimos provident. Ipsum consequatur qui corporis similique libero asperiores sed. Et libero nobis voluptatibus facere. Alias quia eos nemo ipsam et. Rerum possimus perferendis non deserunt mollitia. Impedit omnis atque voluptas ut voluptatem id. Autem tempore exercitationem corrupti reprehenderit est ea pariatur consectetur. Voluptatem delectus quis dignissimos debitis incidunt quasi rerum. Cumque qui cumque a velit eos. Nostrum tempora ad in et praesentium qui. Rerum vel quos eligendi expedita.', '916', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '1', '1', null);
INSERT INTO `articles` VALUES ('43', '2020-07-14', 'est-nulla-voluptatem-deleniti-voluptas-dolor', 'Reprehenderit maiores harum doloribus alias fugiat.', 'Molestiae dolores culpa nihil et tempore repellendus vitae aperiam. Ea dolor sit et voluptatibus. Sed fugit necessitatibus voluptatum vel veniam dolorum numquam. Alias quod necessitatibus quo error. Labore expedita fugit eaque est libero voluptas ea aut. Voluptate vel rerum est distinctio. Nisi et veniam est repellat cupiditate voluptatum possimus iure. Velit aperiam consequatur numquam blanditiis. Consequatur minima sunt qui blanditiis. Iusto tenetur sed aspernatur cum officia quia. Iusto qui aut suscipit dolor quo qui ex molestias. Earum laudantium voluptatibus architecto perferendis asperiores atque quia. Quibusdam qui est eligendi et accusamus modi. Aliquid dolorem non est. Perferendis et similique laborum qui aut. Consequuntur tempora accusantium velit et. Facere quam illum pariatur doloribus ut in. Ad id iure dignissimos est possimus ut eos.', '486', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '1', '1', null);
INSERT INTO `articles` VALUES ('44', '2020-09-11', 'ut-voluptates-earum-sed-iusto-ullam-eos-qui', 'Voluptas est laboriosam optio quidem quod sit et.', 'Nobis numquam illo expedita eum adipisci sit minima. Id porro enim nostrum nisi quaerat. In autem iste voluptatum ipsam autem molestiae quam. Libero iusto ea numquam. Modi quod debitis architecto culpa. Nihil quia sint magni at. Nesciunt repudiandae ab omnis nostrum dicta dolor. Praesentium quia impedit vel voluptatibus dolores unde quae. Suscipit expedita possimus provident reprehenderit cupiditate natus. Voluptas aperiam tempora quidem qui sunt. Praesentium tempora distinctio quasi quisquam. Commodi vero quo reprehenderit est adipisci officiis harum. Est nostrum nobis voluptatem qui. Ut est soluta eos sint. Commodi ducimus officiis et esse doloribus. Et hic vel et et quibusdam. Et eos voluptatibus vitae sapiente. Perspiciatis ut provident reiciendis a quibusdam.', '254', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('45', '2020-08-13', 'dolores-enim-rerum-sunt-iste-veniam-harum-earum', 'Consectetur enim sed sequi qui nihil at.', 'Eum eaque et consectetur qui. Et et asperiores expedita praesentium dolor natus suscipit. Sed et nam corporis porro in. Voluptatem vel voluptates sit est nisi porro. Quia ea non itaque qui ex. Nesciunt et recusandae ratione et. Fuga facere nihil alias quia quis nobis laboriosam sed. Qui omnis quod enim dolor. Soluta illum sint quisquam et sunt expedita modi. Aspernatur doloribus repudiandae est. Quis ex consequatur non asperiores excepturi porro. Adipisci commodi soluta rerum. Aut et a ullam temporibus. Neque quod qui ut est. Reiciendis magnam odio fugiat iusto eligendi. Saepe voluptas saepe voluptas. Pariatur vel ex ratione soluta blanditiis minima facilis. Qui aut ratione quisquam voluptate beatae earum. Et cum facilis eligendi quaerat atque consequuntur. Et excepturi sed minus et libero saepe similique.', '130', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '1', '1', null);
INSERT INTO `articles` VALUES ('46', '2020-07-13', 'debitis-aperiam-vel-id-quia-aut-modi', 'Cupiditate fuga id omnis.', 'Eos facilis ducimus enim est molestiae. Quod voluptatem consequatur ex magni tempora. Ut nulla et ut aut iure voluptatem vel. Consequatur dolorum sint dolorem dignissimos ut. Recusandae reprehenderit quisquam ut quisquam delectus. Commodi accusamus corporis ut enim voluptas voluptas facilis. Omnis aut aliquam consequatur ut eaque quas laboriosam. Vel quia voluptate porro sint ad pariatur placeat. Omnis illum enim in. A et sapiente qui sed. Eveniet dicta nam ut aliquam. Ea rerum necessitatibus tenetur a nobis illo saepe ducimus. Et expedita tempore numquam est. Quaerat quo dolore enim molestiae facere unde. Assumenda ea nostrum aut consequuntur labore. Quod reprehenderit et ut dolores voluptatum. Error eos dolor velit ut autem odit facere. Ducimus nulla hic qui nemo. Hic exercitationem perferendis quia. Et consequatur quas sunt repudiandae nesciunt excepturi. Omnis totam et incidunt quia quia suscipit.', '245', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '3', '2', '1', null);
INSERT INTO `articles` VALUES ('47', '2020-05-13', 'explicabo-quam-odit-sequi-eaque-qui', 'Quae aliquam officia maxime qui.', 'Aut alias quo perferendis eaque ipsa. Maiores ad ut quia molestias nisi ratione animi. Facere officia et nostrum esse eum numquam voluptas. Cupiditate distinctio voluptatem fugit neque. Illum id ut quisquam et. Sapiente aut molestiae ipsa eos ut blanditiis. Itaque ut consequatur quos voluptates ea quasi placeat. Velit facilis ratione similique consequatur delectus. Nemo non ut modi quia doloremque occaecati. Mollitia et blanditiis nostrum suscipit. Ad perspiciatis porro earum inventore cumque. Excepturi repellendus sunt minima hic ea blanditiis. Laborum voluptas ducimus eveniet omnis debitis est sunt. Fugiat sunt dolores repellendus eligendi porro cum. Voluptatem accusantium et at soluta et fugit beatae. Laborum ad qui sunt labore impedit et. Commodi soluta dolorum aspernatur et laboriosam sunt. Ad porro et aut soluta ipsa amet. Aliquid ipsam alias eos iusto non. Laboriosam eaque placeat quisquam sit facere officia.', '971', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('48', '2019-12-23', 'deleniti-dolorem-ut-ullam-eius-harum-nemo', 'Minus tenetur non quam tempore facilis.', 'Quis quae eveniet enim suscipit inventore. Exercitationem architecto culpa quos placeat. Quisquam modi nostrum alias consequatur ullam in. At voluptas aliquid illo ea ut omnis. Expedita et inventore laboriosam. Et est neque quos. Enim et consequatur vitae architecto dignissimos et quod sapiente. Laudantium dignissimos consequatur labore dicta odio. Dicta necessitatibus similique nemo earum rerum est. Nostrum deserunt et sed dolores rerum explicabo illum quae. Eos nobis corrupti doloribus aut reprehenderit debitis. Tenetur ipsa qui minus placeat et et. Dolor et et fugiat voluptas quidem velit est culpa. Ipsum aut voluptates doloremque dignissimos quis. Enim et voluptatem qui excepturi enim. Voluptas et excepturi fuga impedit nihil. Doloribus repellendus culpa dolorem voluptatem porro omnis. Aut iste et inventore voluptatem a.', '575', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '4', '1', '1', null);
INSERT INTO `articles` VALUES ('49', '2020-08-23', 'ducimus-maxime-alias-eveniet-vel-provident-sint-hic', 'Ipsam sit provident nostrum voluptatibus.', 'Ut debitis soluta hic laudantium blanditiis molestiae saepe. Ullam corporis eaque optio quia. Totam tempore sint quis id. Necessitatibus nihil sed voluptates nihil distinctio tempore. Amet esse sit numquam incidunt. Repudiandae rerum fuga quo quia veritatis qui atque. Voluptatum et facere voluptatem explicabo vitae dolore. In reprehenderit delectus id aut. Rerum doloremque aut voluptatem nulla porro. Libero qui laudantium ex. Ipsam qui incidunt voluptatibus consequatur quos sint laborum. Praesentium dolores voluptas ut omnis omnis hic enim. Sit officiis adipisci consequatur rem soluta. Assumenda sint id voluptatem aut dolor quia molestias laborum. Quos ducimus fugit quae inventore rerum quas non. Unde hic eos sit architecto. Quis dolor corrupti eum ut a laboriosam quis. Officiis praesentium aliquam voluptatum est sequi accusantium. Debitis reprehenderit cum quo libero et nemo. Eaque quam est at cumque omnis quia. Enim aliquid ab aut. Sunt illum et dolorem ea ut.', '428', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '2', '1', '1', null);
INSERT INTO `articles` VALUES ('50', '2020-08-06', 'eum-laboriosam-consectetur-repudiandae-velit', 'Est eos alias itaque dicta facere.', 'Optio velit nam odit. Et et tenetur sint est. Qui modi nobis eum ut voluptatem ipsam et. Voluptatibus libero in illo quis aut ipsum iste. A adipisci aut aperiam ipsa recusandae est ab. Culpa vero et dolores vero debitis aut aut. Quos incidunt beatae ratione et qui porro. Consequatur voluptatem nihil ipsum ex minus itaque. Reiciendis vero rerum non culpa quidem distinctio. Eos provident occaecati nesciunt ex. Sed esse quos nam odit. Temporibus in quam laboriosam labore expedita ipsa. Delectus dolores dolor repellendus amet nulla sed laborum similique. Commodi sed ipsa illum at. Quaerat facere id et. Optio alias qui et. Eveniet ipsa molestiae aut eos et ut minus maiores. Velit porro vero dolorum autem ut. Saepe sint sunt eum dolorem et. Et est tenetur ut architecto itaque voluptas accusantium. Harum enim libero qui nobis. Est dolor commodi nisi mollitia veritatis ad. Molestiae sunt ipsam quia. Reiciendis at culpa modi nam perspiciatis. Aut voluptates est placeat architecto doloremque.', '332', 'https://www.youtube.com/embed/UaaoBac2TTE', '2020-10-04 15:58:21', '2020-10-04 15:58:21', '1', '2', '1', null);

-- ----------------------------
-- Table structure for `article_photos`
-- ----------------------------
DROP TABLE IF EXISTS `article_photos`;
CREATE TABLE `article_photos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `article_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `article_photos_article_id_foreign` (`article_id`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of article_photos
-- ----------------------------
INSERT INTO `article_photos` VALUES ('1', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '1', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('2', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '2', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('3', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '3', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('4', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '4', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('5', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '5', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('6', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '6', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('7', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '7', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('8', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '8', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('9', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '9', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('10', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '10', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `article_photos` VALUES ('11', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '11', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('12', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '12', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('13', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '13', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('14', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '14', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('15', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '15', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('16', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '16', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('17', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '17', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('18', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '18', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('19', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '19', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('20', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '20', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('21', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '21', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('22', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '22', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('23', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '23', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('24', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '24', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('25', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '25', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('26', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '26', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('27', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '27', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('28', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '28', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('29', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '29', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('30', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '30', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('31', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '31', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('32', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '32', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('33', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '33', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('34', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '34', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('35', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '35', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('36', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '36', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('37', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '37', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('38', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '38', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('39', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '39', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('40', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '40', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('41', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '41', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('42', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '42', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('43', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '43', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('44', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '44', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('45', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '45', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('46', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '46', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('47', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '47', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('48', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '48', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('49', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '49', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);
INSERT INTO `article_photos` VALUES ('50', 'default-imge', 'photo', 'images/uploads/file/image-default.png', '50', '2020-10-04 15:58:22', '2020-10-04 15:58:22', null);

-- ----------------------------
-- Table structure for `categories`
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `categories_slug_index` (`slug`(250))
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO `categories` VALUES ('1', 'sport-new', 'Entertainment', 'Entertainment new!!!', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `categories` VALUES ('2', 'sport-new', 'Sports', 'Sport new!!!', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `categories` VALUES ('3', 'sport-new', 'Technology', 'Technology new!!!', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `categories` VALUES ('4', 'sport-new', 'Social', 'Social new!!!', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);

-- ----------------------------
-- Table structure for `failed_jobs`
-- ----------------------------
DROP TABLE IF EXISTS `failed_jobs`;
CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of failed_jobs
-- ----------------------------

-- ----------------------------
-- Table structure for `migrations`
-- ----------------------------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of migrations
-- ----------------------------
INSERT INTO `migrations` VALUES ('1', '2014_10_12_000000_create_users_table', '1');
INSERT INTO `migrations` VALUES ('2', '2014_10_12_100000_create_password_resets_table', '1');
INSERT INTO `migrations` VALUES ('3', '2016_06_01_000001_create_oauth_auth_codes_table', '1');
INSERT INTO `migrations` VALUES ('4', '2016_06_01_000002_create_oauth_access_tokens_table', '1');
INSERT INTO `migrations` VALUES ('5', '2016_06_01_000003_create_oauth_refresh_tokens_table', '1');
INSERT INTO `migrations` VALUES ('6', '2016_06_01_000004_create_oauth_clients_table', '1');
INSERT INTO `migrations` VALUES ('7', '2016_06_01_000005_create_oauth_personal_access_clients_table', '1');
INSERT INTO `migrations` VALUES ('8', '2019_08_19_000000_create_failed_jobs_table', '1');
INSERT INTO `migrations` VALUES ('9', '2020_06_23_061122_add_deleted_at_to_users_table', '1');
INSERT INTO `migrations` VALUES ('10', '2020_07_21_065149_create_categories_table', '1');
INSERT INTO `migrations` VALUES ('11', '2020_07_21_065328_create_articles_table', '1');
INSERT INTO `migrations` VALUES ('12', '2020_07_28_132630_change_field_type_to_articles_table', '1');
INSERT INTO `migrations` VALUES ('13', '2020_07_29_034807_create_article_photos_table', '1');
INSERT INTO `migrations` VALUES ('14', '2020_07_29_071501_create_roles_table', '1');
INSERT INTO `migrations` VALUES ('15', '2020_07_29_074828_add_field_role_id_to_users_table', '1');
INSERT INTO `migrations` VALUES ('16', '2020_08_02_032907_change_field_article_to_articles_table', '1');
INSERT INTO `migrations` VALUES ('17', '2020_10_03_023917_add_field_to_articles', '1');
INSERT INTO `migrations` VALUES ('18', '2020_10_03_052406_add_field_soft_delete_to_articles', '1');

-- ----------------------------
-- Table structure for `oauth_access_tokens`
-- ----------------------------
DROP TABLE IF EXISTS `oauth_access_tokens`;
CREATE TABLE `oauth_access_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `client_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `oauth_access_tokens_user_id_index` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of oauth_access_tokens
-- ----------------------------

-- ----------------------------
-- Table structure for `oauth_auth_codes`
-- ----------------------------
DROP TABLE IF EXISTS `oauth_auth_codes`;
CREATE TABLE `oauth_auth_codes` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `client_id` bigint(20) unsigned NOT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `oauth_auth_codes_user_id_index` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of oauth_auth_codes
-- ----------------------------

-- ----------------------------
-- Table structure for `oauth_clients`
-- ----------------------------
DROP TABLE IF EXISTS `oauth_clients`;
CREATE TABLE `oauth_clients` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redirect` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `personal_access_client` tinyint(1) NOT NULL,
  `password_client` tinyint(1) NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `oauth_clients_user_id_index` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of oauth_clients
-- ----------------------------

-- ----------------------------
-- Table structure for `oauth_personal_access_clients`
-- ----------------------------
DROP TABLE IF EXISTS `oauth_personal_access_clients`;
CREATE TABLE `oauth_personal_access_clients` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `client_id` bigint(20) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of oauth_personal_access_clients
-- ----------------------------

-- ----------------------------
-- Table structure for `oauth_refresh_tokens`
-- ----------------------------
DROP TABLE IF EXISTS `oauth_refresh_tokens`;
CREATE TABLE `oauth_refresh_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `access_token_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `oauth_refresh_tokens_access_token_id_index` (`access_token_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of oauth_refresh_tokens
-- ----------------------------

-- ----------------------------
-- Table structure for `password_resets`
-- ----------------------------
DROP TABLE IF EXISTS `password_resets`;
CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`(250))
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of password_resets
-- ----------------------------

-- ----------------------------
-- Table structure for `roles`
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('1', 'Super Admin', 'Super Admin Role', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);
INSERT INTO `roles` VALUES ('2', 'Admin', 'Admin Role', '2020-10-04 15:58:21', '2020-10-04 15:58:21', null);

-- ----------------------------
-- Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `f_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `l_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `role_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`) USING HASH,
  KEY `users_role_id_foreign` (`role_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('1', 'Chan', 'Chea', 'superadmin@gmail.com', null, '$2y$10$UkanRhOQLBDmpXBjl58O7.LgPYMOyfZ86nzxwTF2KrG6j0qYizxoq', null, '2020-10-04 15:58:21', '2020-10-04 15:58:21', null, '1');
INSERT INTO `users` VALUES ('2', 'Devit', 'Chea', 'admin@gmail.com', null, '$2y$10$0zGgnWr/KB83i5gue6rPBO1p7D12qM0M09V./DDy8QsqyGmT9QJmq', null, '2020-10-04 15:58:21', '2020-10-04 15:58:21', null, '2');
